/**
 * Core types for TianGong Agent
 */

import type { AgentMessage } from "@mariozechner/pi-agent-core";

// ============================================================================
// User & Authentication
// ============================================================================

export interface TianUser {
	id: string;
	email: string;
	name: string;
	department: string;
	role: "engineer" | "citizen_developer" | "manager" | "admin";
	preferences: UserPreferences;
}

export interface UserPreferences {
	/** UI mode preference */
	uiMode: "tui" | "web";
	/** Default model to use */
	defaultModel: string;
	/** Default provider */
	defaultProvider: string;
	/** Thinking level */
	thinkingLevel: "off" | "minimal" | "low" | "medium" | "high";
	/** Enable session persistence */
	persistSessions: boolean;
	/** Auto-checkpoint interval (minutes, 0 = disabled) */
	autoCheckpointInterval: number;
	/** Notification preferences */
	notifications: {
		email: boolean;
		slack: boolean;
	};
	apiKeys: Record<string, string>;
}

// ============================================================================
// Tasks
// ============================================================================

export interface TianTask {
	id: string;
	name: string;
	description: string;
	status: TaskStatus;
	progress: number;
	userId: string;
	sessionId: string;
	createdAt: Date;
	updatedAt: Date;
	completedAt?: Date;
	metadata: TaskMetadata;
}

export type TaskStatus = "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";

export interface TaskMetadata {
	/** Task template used (if any) */
	templateId?: string;
	/** Associated policy IDs */
	policyIds?: string[];
	/** Associated claim IDs */
	claimIds?: string[];
	/** Department */
	department?: string;
	/** Priority */
	priority?: "low" | "medium" | "high" | "urgent";
	/** Due date */
	dueDate?: Date;
	/** Tags */
	tags?: string[];
	/** Custom fields */
	custom?: Record<string, unknown>;
}

export interface TaskCheckpoint {
	id: string;
	taskId: string;
	timestamp: Date;
	summary: string;
	messageIndex: number;
	pendingActions: string[];
	autoGenerated: boolean;
}

// ============================================================================
// Task Templates
// ============================================================================

export interface TaskTemplate {
	id: string;
	name: string;
	description: string;
	category: TaskCategory;
	icon: string;
	estimatedTime: string;
	skills: string[];
	systemPromptExtension?: string;
	defaultInput?: string;
	approvalRequired?: boolean;
}

export type TaskCategory =
	| "policy_management"
	| "claims_processing"
	| "document_generation"
	| "reporting"
	| "data_validation"
	| "compliance"
	| "custom";

// ============================================================================
// Sessions
// ============================================================================

export interface TianSession {
	id: string;
	userId: string;
	taskId?: string;
	createdAt: Date;
	updatedAt: Date;
	messages: AgentMessage[];
	checkpoints: TaskCheckpoint[];
	metadata: SessionMetadata;
}

export interface SessionMetadata {
	uiMode: "tui" | "web";
	model: string;
	provider: string;
	workspaceDir: string;
	tokensUsed: number;
	cost: number;
}

// ============================================================================
// Tools
// ============================================================================

export interface TianToolConfig {
	/** Tool name */
	name: string;
	/** Whether tool is enabled */
	enabled: boolean;
	/** Approval required before execution */
	approvalRequired: boolean;
	/** Max executions per session (0 = unlimited) */
	maxExecutions: number;
	/** Allowed user roles */
	allowedRoles: TianUser["role"][];
}

// ============================================================================
// API Configuration
// ============================================================================

export interface ApiKeyConfig {
	/** Provider name (e.g., 'openai', 'anthropic', 'azure-openai') */
	provider: string;
	/** API key */
	apiKey: string;
	/** Optional base URL for custom endpoints */
	baseUrl?: string;
	/** Optional model ID */
	modelId?: string;
}

// ============================================================================
// Server Configuration
// ============================================================================

export interface TianConfig {
	/** Server port */
	port: number;
	/** Server host */
	host: string;
	/** Agent directory for sessions, settings, etc. */
	agentDir: string;
	/** Default workspace directory */
	workspaceDir: string;
	/** System-level API keys (shipped with deployment) */
	apiKeys?: ApiKeyConfig[];
	/** Default model configuration */
	defaultModel: {
		provider: string;
		modelId: string;
	};
	/** Session configuration */
	session: {
		/** Session timeout in minutes */
		timeoutMinutes: number;
		/** Max sessions per user */
		maxPerUser: number;
		/** Enable session persistence */
		persist: boolean;
	};
	/** Security configuration */
	security: {
		/** Enable audit logging */
		auditLogging: boolean;
		/** Rate limit requests per minute */
		rateLimit: number;
		/** Allowed origins for CORS */
		allowedOrigins: string[];
	};
}

// ============================================================================
// WebSocket Messages
// ============================================================================

export interface WSMessage {
	type: string;
	payload?: unknown;
}

export interface WSInputMessage extends WSMessage {
	type: "input";
	payload: {
		data: string;
	};
}

export interface WSResizeMessage extends WSMessage {
	type: "resize";
	payload: {
		cols: number;
		rows: number;
	};
}

export interface WSOutputMessage extends WSMessage {
	type: "output";
	payload: {
		data: string;
	};
}

export interface WSConnectedMessage extends WSMessage {
	type: "connected";
	payload: {
		sessionId: string;
		cols: number;
		rows: number;
		uiMode: "tui" | "web";
	};
}

export interface WSExitMessage extends WSMessage {
	type: "exit";
	payload: {
		exitCode: number;
		signal?: string;
	};
}

export interface WSErrorMessage extends WSMessage {
	type: "error";
	payload: {
		message: string;
		code?: string;
	};
}

// ============================================================================
// API Response Types
// ============================================================================

export interface APITaskListResponse {
	tasks: TianTask[];
	total: number;
	page: number;
	pageSize: number;
}

export interface APISessionListResponse {
	sessions: TianSession[];
	total: number;
}

export interface APIErrorResponse {
	error: string;
	message: string;
	details?: Record<string, unknown>;
}
